[package]
edition = "2021"
name = "squirrel"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cfg-if = "1"
pollster = "0.3"
raw-window-handle = "0.6"
tracing-log = {version = "0.1", features = ["env_logger"]}
wgpu = "0.18"
winit = {version = "0.28.7", features = ["android-native-activity"]}

[target.'cfg(target_arch = "wasm32")'.dependencies]
console_error_panic_hook = "0.1"
console_log = "1.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = {version = "0.3", features = [
  "Document",
  "Window",
  "Element",
]}
wgpu = {version = "0.18", features = ["webgl"]}
